services:
  ldap:
    image: osixia/openldap:latest
    container_name: openldap-osixia
    command: ["--copy-service"]
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=informatica
      - LDAP_DOMAIN=test.tierno.es
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
    volumes:
      - ../ldap/ldif-clean:/container/service/slapd/assets/config/bootstrap/ldif/custom
    restart: unless-stopped
    network_mode: host

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host

  laravel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8080:8080"
    environment:
      - LDAP_HOST=172.19.0.3
      - LDAP_PORT=389
      - LDAP_BASE_DN=dc=test,dc=tierno,dc=es
      - LDAP_USERNAME=cn=admin,dc=test,dc=tierno,dc=es
      - LDAP_PASSWORD=admin
      - LDAP_AUTH_LOGIN_FALLBACK=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    volumes:
      - ../proyecto:/var/www/html
      - document_data:/var/www/html/public/documentos
      - laravel_logs:/var/www/html/storage/logs
    depends_on:
      - ldap
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    network_mode: host

  terminal-server:
    build:
      context: ../terminal-server
      dockerfile: Dockerfile
    container_name: terminal-server
    restart: unless-stopped
    ports:
      - "8081:8081"
    user: root
    network_mode: host

  webssh2:
    build:
      context: ../webssh2
      dockerfile: Dockerfile
    container_name: webssh2
    restart: unless-stopped
    ports:
      - "2222:2222"
    environment:
      - SSHHOST=0.0.0.0
      - SSHPORT=22
      - SSHUSER=root
      - SSHKEY=/config/id_rsa
    volumes:
      - ../webssh2/app/config.json:/config.json:ro
      - ../webssh2/config:/config
      - ../webssh2/config/id_rsa:/config/id_rsa:ro
    network_mode: host

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  document_data:
    driver: local
  laravel_logs:
    driver: local