services:
  ldap:
    build:
      context: ../ldap
      dockerfile: Dockerfile
    container_name: openldap-osixia
    user: root
    environment:
      - LDAP_ORGANISATION=IES TIERNO GALVAN
      - LDAP_DOMAIN=tierno.es
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=admin
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_TLS=true
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_TLS_CRT_FILENAME=cert.pem
      - LDAP_TLS_KEY_FILENAME=privkey.pem
      - LDAP_TLS_CA_CRT_FILENAME=chain.pem
      - LDAP_TLS_CIPHER_SUITE=SECURE256:-VERS-SSL3.0
      - LDAP_TLS_PROTOCOL_MIN=3.1
      - LDAP_BOOTSTRAP=true
      - LDAP_FORCE_BOOTSTRAP=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_READONLY_USER=false
      - LDAP_BOOTSTRAP_LDIF_ORDER=01-config-password.ldif,01-ou.ldif,02-ldap-admin-user.ldif,20_acl.ldif,03-ldapadmins-group.ldif,04-everybody-group.ldif,05-alumnos-users.ldif,06-alumnos-groups.ldif,07-profesor-users.ldif,08-profesores-group.ldif,09-docker-group.ldif,10-lastUID-GID.ldif,11-sudo-schema.ldif,12-sudo-profesores.ldif,13-uniqueMember-index.ldif
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ../ldap/certs/cert-tierno.es:/container/service/slapd/assets/certs
      - ../ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - app-network
    restart: on-failure:3
    stop_grace_period: 30s
    command: ["--loglevel", "debug"]
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldaps://localhost:636", "-b", "dc=tierno,dc=es", "-D", "cn=admin,dc=tierno,dc=es", "-w", "admin"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  laravel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - LDAP_HOST=ldap
      - LDAP_PORT=636
      - LDAP_BASE_DN=dc=tierno,dc=es
      - LDAP_USERNAME=cn=admin,dc=tierno,dc=es
      - LDAP_PASSWORD=admin
      - LDAP_AUTH_LOGIN_FALLBACK=false
      # Variables LdapRecord específicas
      - LDAP_DEFAULT_HOSTS=ldap
      - LDAP_DEFAULT_PORT=636
      - LDAP_DEFAULT_BASE_DN=dc=tierno,dc=es
      - LDAP_DEFAULT_USERNAME=cn=admin,dc=tierno,dc=es
      - LDAP_DEFAULT_SSL=false
      - LDAP_DEFAULT_TLS=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    volumes:
      - ../proyecto:/var/www/html
      - document_data:/var/www/html/public/documentos
      - ../ldap/certs/cert-tierno.es/fullchain.pem:/etc/ssl/certs/site/certificate.crt
      - ../ldap/certs/cert-tierno.es/privkey.pem:/etc/ssl/certs/site/private.key
      - ../ldap/certs/cert-tierno.es/chain.pem:/etc/ssl/certs/site/ca_bundle.crt
      - ../ldap/certs/cert-tierno.es/fullchain.pem:/etc/ssl/certs/ldap/cert.pem
      - ../ldap/certs/cert-tierno.es/privkey.pem:/etc/ssl/certs/ldap/privkey.pem
      - ../ldap/certs/cert-tierno.es/chain.pem:/etc/ssl/certs/ldap/fullchain.pem
    depends_on:
      - ldap
      - mysql
    networks:
      app-network:
        ipv4_address: 172.20.0.6
    healthcheck:
      test: ["CMD", "curl", "-f", "-L", "https://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: >
      bash -c "echo '172.20.0.6 ldap.tierno.es' >> /etc/hosts && docker-php-entrypoint apache2-foreground"
  webssh2:
    build:
      context: ../webssh2
      dockerfile: Dockerfile
    container_name: webssh2
    restart: unless-stopped
    user: root
    networks:
      app-network:
        ipv4_address: 172.20.0.5
    environment:
      - TZ=Europe/Madrid
    ports:
      - "2222:2222"
  macscanner:
    build:
      context: ../macscanner
      dockerfile: Dockerfile
    container_name: macscanner
    restart: unless-stopped
    network_mode: host
    user: root
    environment:
      - TZ=Europe/Madrid
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  mysql_data:
  document_data:
    driver: local
  ldap_data:
  ldap_config:
  ldap_tls_config: