services:
  ldap:
    build:
      context: ../ldap
      dockerfile: Dockerfile
    container_name: openldap-osixia
    environment:
      LDAP_ORGANISATION: "IES TIERNO GALVAN"
      LDAP_DOMAIN: "tierno.es"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "admin"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_TLS: "true"
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_CRT_FILENAME: "cert.pem"
      LDAP_TLS_KEY_FILENAME: "privkey.pem"
      LDAP_TLS_CA_CRT_FILENAME: "fullchain.pem"
      LDAP_BACKEND: "mdb"
      LDAP_READONLY_USER: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_NOFILE: "1024"
    volumes:
      - ../ldap/certs/cert-tierno.es:/container/service/slapd/assets/certs
      - ../ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  laravel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - LDAP_HOST=ldap
      - LDAP_PORT=636
      - LDAP_BASE_DN=dc=tierno,dc=es
      - LDAP_USERNAME=cn=admin,dc=tierno,dc=es
      - LDAP_PASSWORD=admin
      - LDAP_AUTH_LOGIN_FALLBACK=false
      # Variables LdapRecord específicas
      - LDAP_DEFAULT_HOSTS=ldap
      - LDAP_DEFAULT_PORT=636
      - LDAP_DEFAULT_BASE_DN=dc=tierno,dc=es
      - LDAP_DEFAULT_USERNAME=cn=admin,dc=tierno,dc=es
      - LDAP_DEFAULT_SSL=true
      - LDAP_DEFAULT_TLS=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    volumes:
      - ../proyecto:/var/www/html
      - document_data:/var/www/html/public/documentos
      - ../ldap/certs/cert-tierno.es/fullchain.pem:/etc/ssl/certs/site/certificate.crt
      - ../ldap/certs/cert-tierno.es/privkey.pem:/etc/ssl/certs/site/private.key
      - ../ldap/certs/cert-tierno.es/chain.pem:/etc/ssl/certs/site/ca_bundle.crt
    depends_on:
      - ldap
      - mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  webssh2:
    build:
      context: ../webssh2
      dockerfile: Dockerfile
    container_name: webssh2
    restart: unless-stopped
    ports:
      - "2222:2222"
    environment:
      - SSHHOST=0.0.0.0
      - SSHPORT=22
      - SSHUSER=root
      - SSHKEY=/config/id_rsa
    volumes:
      - ../webssh2/app/config.json:/usr/src/app/config.json:ro
      - ../webssh2/config:/config
      - ../webssh2/config/id_rsa:/config/id_rsa:ro
    networks:
      - app-network
  macscanner:
    build:
      context: ../macscanner
      dockerfile: Dockerfile
    container_name: macscanner
    restart: unless-stopped
    network_mode: host
    user: root
    environment:
      - TZ=Europe/Madrid
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  document_data:
    driver: local
  ldap_data:
  ldap_config: